---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: site/data
  label: Data
  create: all
  match: "*.toml"
  new_doc_ext: toml
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/content/things
  label: Things
  create: all
  match: "**/*"
- type: directory
  path: site/content/auctions
  label: Auctions
  create: all
  match: "**/*"
upload_dir: site/static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.74.2
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: dist
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk -d public
version: 0.57.1
